name: mershed
description: "AI-powered travel guide for Saudi Arabia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.14.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  provider: ^6.1.1
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  uuid: ^4.4.0
  flutter_svg: ^2.0.17
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_2fa: ^1.0.4
  flutter_dotenv: ^5.1.0
  flutter_map_tile_caching: ^9.0.1
  flutter_polyline_points: ^2.1.0
  shared_preferences: ^2.3.0
  fl_chart: ^0.70.2
  animate_do: ^4.2.0
  connectivity_plus: ^6.0.5
  google_sign_in: ^6.2.1
  permission_handler: ^11.4.0
  responsive_framework: ^1.5.1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - .env
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700