// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiG6tkrWGhKAZ08XyKQaTlZ7a33EBMzfQ',
    appId: '1:50034881834:web:8e9701d8de26688b51da53',
    messagingSenderId: '50034881834',
    projectId: 'mershed-661af',
    authDomain: 'mershed-661af.firebaseapp.com',
    storageBucket: 'mershed-661af.firebasestorage.app',
    measurementId: 'G-QP7BXL9JFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBql7dkU-aWPkT-NS_BbhoC6svjEadm9k8',
    appId: '1:50034881834:android:00c47c77c3f4489651da53',
    messagingSenderId: '50034881834',
    projectId: 'mershed-661af',
    storageBucket: 'mershed-661af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-52e5caonw1mQxTiYyuaOyUB3kTnbiM',
    appId: '1:50034881834:ios:deff3bbdf679104051da53',
    messagingSenderId: '50034881834',
    projectId: 'mershed-661af',
    storageBucket: 'mershed-661af.firebasestorage.app',
    iosBundleId: 'com.example.mershed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI-52e5caonw1mQxTiYyuaOyUB3kTnbiM',
    appId: '1:50034881834:ios:deff3bbdf679104051da53',
    messagingSenderId: '50034881834',
    projectId: 'mershed-661af',
    storageBucket: 'mershed-661af.firebasestorage.app',
    iosBundleId: 'com.example.mershed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiG6tkrWGhKAZ08XyKQaTlZ7a33EBMzfQ',
    appId: '1:50034881834:web:a92f99584c1f420b51da53',
    messagingSenderId: '50034881834',
    projectId: 'mershed-661af',
    authDomain: 'mershed-661af.firebaseapp.com',
    storageBucket: 'mershed-661af.firebasestorage.app',
    measurementId: 'G-23WZW92BZL',
  );
}
